import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "assistant-ui Starter App",
  description: "Generated by create-assistant-ui",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
  <main className="min-h-screen flex flex-col">
    <div className="flex-grow">
      {children}
    </div>
    
    {/* ✅ Your Footer Here */}
    <footer className="text-center text-sm text-gray-500 py-4 border-t">
      Built with ❤️ by{"Debraj Naskar"}
      <a
        href="https://github.com/debrajnaskar"
        target="_blank"
        rel="noopener noreferrer"
        className="text-blue-600 underline"
      >
        Debraj Naskar
      </a>
    </footer>
  </main>
</body>
    </html>
  );
}
